name: Sync
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote add -f source https://github.com/ipfs-examples/examples-source.git # change to the proper source url
          git checkout -b upstream source/main # change to the proper branch
          git subtree split -P examples/example1 -b example # change "examples/example1" to the proper folder
          git checkout master
          git merge -s recursive -Xtheirs example --allow-unrelated-histories --no-edit
          git push
