name: Sync
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # Helper function to check if repo exist
          git-remote-url-reachable() {
            git ls-remote "$1" CHECK_GIT_REMOTE_URL_REACHABILITY >/dev/null 2>&1
          }

          ####### region: Configurations

          GITHUB_USERNAME="github-actions"
          GITHUB_EMAIL="github-actions@github.com"

          # change to the proper source url, branch and folder
          DESTINATION_REPO_NAME="ipfs-examples/examples-source"
          DESTINATION_BRANCH="main"
          DESTINATION_FOLDER_PATH="examples/example1"

          ####### endregion: Configurations

          REPO_URL="git://github.com/$DESTINATION_REPO_NAME"
          DESTINATION_URL="https://github.com/$DESTINATION_REPO_NAME.git"

          if ! git-remote-url-reachable $REPO_URL
          then
            echo "The repository $DESTINATION_REPO_NAME does not exist."

            exit 1
          fi
        
          echo "Set git configurations"
          git config user.name "$GITHUB_USERNAME"
          git config user.email "$GITHUB_EMAIL"
          
          echo "Check if repo exists"
          git remote add -f source "$DESTINATION_URL"
          git checkout -b upstream "source/$DESTINATION_BRANCH"
          
          echo "Get latest files"
          git subtree split -P "$DESTINATION_FOLDER_PATH" -b example
          git checkout master
          
          git diff master..example
          git merge -s recursive -Xtheirs example --allow-unrelated-histories --no-edit

          echo "Log git status:"
          git status

          echo "Check if exist changes and push changes"
          if git diff-index --quiet HEAD
          then
              echo "Does not exist any changes."
          else
              echo "Pushing changes..."
              git push
          fi
